spring.application.name=MiyanoHime

# H2 Databaseの設定 (ファイルとして保存する設定)
# ./data/demo というファイルに保存されます
spring.datasource.url=jdbc:h2:file:./data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2コンソール (ブラウザでDBを見る画面) を有効にする
spring.h2.console.enabled=true

# JPAの設定 (Javaクラスから自動でテーブルを作る機能)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 警告を消すための設定（現状の挙動を明示的にOKする）
spring.jpa.open-in-view=true